spotlight:
  default_visibility: show # Optional, defaults to "show"
  categories:
    core:
      label: "Core Metrics"
      color: blue
    experimental:
      label: "Experimental Metrics"
      color: orange
    sales:
      label: "Sales"
      color: green
parameters:
  min_order_amount:
    label: "Minimum Order Amount ($)"
    description: "Filter orders by minimum amount"
    default: "0"
    options:
      - "0"
      - "10"
      - "25"
      - "50"
      - "100"
  funnel_type:
    label: "Funnel Type"
    description: "Choose which funnel analysis to display"
    default: "customer_journey"
    options:
      - "customer_journey"
      - "ecommerce"
      - "marketing"
  company_quarter:
    label: "Company Quarter"
    description: "Filter orders by company fiscal quarter (Q1: Mar-May, Q2: Jun-Aug, Q3: Sep-Nov, Q4: Dec-Feb)"
    default: "all"
    options:
      - "all"
      - "LDQ1"
      - "LDQ2"
      - "LDQ3"
      - "LDQ4"
